security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        backoffice:
            pattern: ^/
            form_login:
                check_path: /backoffice/login
                provider: fos_userbundle
                success_handler: togu.user.authentication_handler
                failure_handler: togu.user.authentication_handler
                require_previous_session: false
            logout:
                path:   /backoffice/logout
                
            anonymous:    true

    access_control:
        - { path: ^/backoffice/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        