<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Togu\ApplicationModelsBundle\Document;

use Togu\ApplicationModelsBundle\Document\BasePage;
use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;
use Tpg\ExtjsBundle\Annotation as Extjs;
use JMS\Serializer\Annotation as JMS;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/index.html
 *
 * @author <yourname> <youremail>
 */
/**
 * @Extjs\Model(name="Togu.applicationModels.Page")
 * @Extjs\ModelProxy(option={"url": "../../backoffice/admin/pages","appendId": true,"batchActions": false}, name="rest")
 *
 * @JMS\ExclusionPolicy("all")
 * @PHPCR\Document(referenceable=true)
 */
class Page extends BasePage
{

}