<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Togu\ApplicationModelsBundle\Document;

use Togu\ApplicationModelsBundle\Document\BaseSection as BaseSection;
use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/index.html
 *
 * @author <yourname> <youremail>
 */
/**
 * @PHPCR\Document(referenceable=true)
 */
class Section extends BaseSection
{
}